# Generated by Django 5.0.7 on 2024-07-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='media/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='CoffeeBaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title1', models.CharField(blank=True, max_length=100, null=True)),
                ('detail', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Coffee Banner',
                'verbose_name_plural': 'Coffee Banners',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Our Blog',
                'verbose_name_plural': 'Our Blogs',
            },
        ),
        migrations.CreateModel(
            name='OurCoffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Our Coffee',
                'verbose_name_plural': 'Our Coffees',
            },
        ),
    ]
